version: '3.8'

services:
  mai-app:
    build: .
    ports:
      - "3000:80"          # host:container
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
