// Daily AI content (generated by the Telegram agent's cron jobs).
// Posts live in src/content/daily/ as YYYY-MM-DD.<type>.<locale>.html where
// <type> is "onthisday" or "ainews" and <locale> is "en" or "sv". Renders,
// per locale: one page per post, an index with the most recent posts, and
// monthly archive pages. Swedish pages fall back to the English content for
// posts published before translations existed.
const fs = require('fs');
const path = require('path');

const DAILY_SRC = path.join(__dirname, '..', 'daily');
const RECENT_LIMIT = 14;

const TYPE_META = {
  onthisday: { badge: 'bg-cyan-900 text-cyan-300' },
  ainews: { badge: 'bg-amber-900 text-amber-300' },
};

const STRINGS = {
  en: {
    typeLabel: { onthisday: 'On this day', ainews: 'AI news' },
    indexTitle: 'Daily AI',
    indexIntro: 'A short essay on this day in computing history and a daily AI news roundup, published automatically.',
    empty: 'No posts yet. New essays and news summaries appear here every day.',
    archive: 'Archive',
    posts: (n) => `${n} post${n === 1 ? '' : 's'}.`,
    allPosts: '← All daily posts',
    backLink: '← Back to Home',
    titleSuffix: 'Museum of AI',
    monthLocale: 'en-GB',
    root: '',
    indexHrefFromIndex: '../index.html',
    indexHrefFromPost: '../../index.html',
  },
  sv: {
    typeLabel: { onthisday: 'På denna dag', ainews: 'AI-nytt' },
    indexTitle: 'Dagens AI',
    indexIntro: 'En kort essä om denna dag i datorhistorien och en daglig AI-nyhetssammanfattning, publicerade automatiskt.',
    empty: 'Inga inlägg ännu. Nya essäer och nyhetssammanfattningar publiceras här varje dag.',
    archive: 'Arkiv',
    posts: (n) => `${n} inlägg.`,
    allPosts: '← Alla dagliga inlägg',
    backLink: '← Till startsidan',
    titleSuffix: 'Museum of AI',
    monthLocale: 'sv-SE',
    root: 'sv/',
    indexHrefFromIndex: '../../index.html',
    indexHrefFromPost: '../../../index.html',
  },
};

function discoverPosts() {
  if (!fs.existsSync(DAILY_SRC)) return [];
  const map = new Map();
  for (const f of fs.readdirSync(DAILY_SRC)) {
    const m = f.match(/^(\d{4}-\d{2}-\d{2})\.(onthisday|ainews)\.(en|sv)\.html$/);
    if (!m) continue;
    const key = `${m[1]}.${m[2]}`;
    if (!map.has(key)) map.set(key, { date: m[1], month: m[1].slice(0, 7), type: m[2], files: {} });
    map.get(key).files[m[3]] = f;
  }
  return [...map.values()]
    .filter((p) => p.files.en)
    .sort((a, b) => (a.date === b.date ? a.type.localeCompare(b.type) : b.date.localeCompare(a.date)));
}

function readPost(post, locale) {
  const file = post.files[locale] || post.files.en;
  return fs.readFileSync(path.join(DAILY_SRC, file), 'utf8');
}

function extractTitle(html, fallback) {
  const m = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  if (!m) return fallback;
  return m[1].replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim() || fallback;
}

function extractExcerpt(html) {
  const m = html.match(/<p[^>]*>([\s\S]*?)<\/p>/i);
  if (!m) return '';
  const text = m[1].replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim();
  return text.length > 180 ? text.slice(0, 180).trimEnd() + '…' : text;
}

function postSlug(post) {
  return `${post.date}-${post.type}`;
}

function monthLabel(month, locale) {
  const [y, m] = month.split('-').map(Number);
  return new Intl.DateTimeFormat(STRINGS[locale].monthLocale, { month: 'long', year: 'numeric' }).format(new Date(y, m - 1, 1));
}

function renderCard(post, hrefPrefix, locale) {
  const s = STRINGS[locale];
  const html = readPost(post, locale);
  const label = s.typeLabel[post.type];
  const title = extractTitle(html, label);
  const excerpt = extractExcerpt(html);
  return `
        <a href="${hrefPrefix}${postSlug(post)}.html" class="glass-card p-6 rounded-xl block hover:border-indigo-400 transition">
          <div class="flex items-center gap-3 mb-2">
            <span class="${TYPE_META[post.type].badge} text-xs font-semibold px-2 py-1 rounded">${label.toUpperCase()}</span>
            <span class="text-slate-400 text-sm">${post.date}</span>
          </div>
          <h2 class="text-xl font-bold">${title}</h2>
          <p class="text-slate-400 mt-2">${excerpt}</p>
        </a>`;
}

function renderIndexContent(posts, months, locale) {
  const s = STRINGS[locale];
  if (posts.length === 0) {
    return `
    <div class="container mx-auto px-4 max-w-3xl">
      <h1 class="text-4xl font-bold mb-6">${s.indexTitle}</h1>
      <p class="text-slate-400">${s.empty}</p>
    </div>`;
  }
  const cards = posts.slice(0, RECENT_LIMIT).map((p) => renderCard(p, 'daily/', locale)).join('\n');
  const archiveLinks = months
    .map((m) => {
      const count = posts.filter((p) => p.month === m).length;
      return `<a href="daily/archive-${m}.html" class="text-cyan-400 hover:text-cyan-300 transition">${monthLabel(m, locale)} (${count})</a>`;
    })
    .join('<span class="text-slate-600 mx-2">·</span>');
  return `
    <div class="container mx-auto px-4 max-w-3xl">
      <h1 class="text-4xl font-bold mb-2">${s.indexTitle}</h1>
      <p class="text-slate-400 mb-10">${s.indexIntro}</p>
      <div class="space-y-6">
${cards}
      </div>
      <div class="mt-12 pt-6 border-t border-slate-800">
        <h2 class="text-lg font-bold mb-3 text-slate-300">${s.archive}</h2>
        <p>${archiveLinks}</p>
      </div>
    </div>`;
}

function renderArchiveContent(month, posts, locale) {
  const s = STRINGS[locale];
  const cards = posts.map((p) => renderCard(p, '', locale)).join('\n');
  return `
    <div class="container mx-auto px-4 max-w-3xl">
      <h1 class="text-4xl font-bold mb-2">${s.indexTitle} — ${monthLabel(month, locale)}</h1>
      <p class="text-slate-400 mb-10">${s.posts(posts.length)}</p>
      <div class="space-y-6">
${cards}
      </div>
      <div class="mt-10">
        <a href="../daily.html" class="text-cyan-400 hover:text-cyan-300 transition">${s.allPosts}</a>
      </div>
    </div>`;
}

function renderPostContent(post, locale) {
  const s = STRINGS[locale];
  const html = readPost(post, locale);
  return `
    <div class="container mx-auto px-4 max-w-3xl">
      <div class="flex items-center gap-3 mb-6">
        <span class="${TYPE_META[post.type].badge} text-xs font-semibold px-2 py-1 rounded">${s.typeLabel[post.type].toUpperCase()}</span>
        <span class="text-slate-400 text-sm">${post.date}</span>
      </div>
      <article class="prose-invert space-y-4 text-slate-300 daily-article daily-article-${post.type}">
${html}
      </article>
      <div class="mt-10">
        <a href="../daily.html" class="text-cyan-400 hover:text-cyan-300 transition">${s.allPosts}</a>
      </div>
    </div>`;
}

function buildLocale(posts, months, locale) {
  const s = STRINGS[locale];
  const out = {};

  out.__index = {
    output: `${s.root}pages/daily.html`,
    lang: locale,
    title: `${s.indexTitle} • ${s.titleSuffix}`,
    assetsPrefix: locale === 'sv' ? '../..' : '..',
    indexHref: s.indexHrefFromIndex,
    backLinkText: s.backLink,
    headExtras: '',
    mainContent: renderIndexContent(posts, months, locale),
    postScripts: '',
  };

  for (const month of months) {
    out[`__archive_${month}`] = {
      output: `${s.root}pages/daily/archive-${month}.html`,
      lang: locale,
      title: `${s.indexTitle} ${monthLabel(month, locale)} • ${s.titleSuffix}`,
      assetsPrefix: locale === 'sv' ? '../../..' : '../..',
      indexHref: s.indexHrefFromPost,
      backLinkText: s.backLink,
      headExtras: '',
      mainContent: renderArchiveContent(month, posts.filter((p) => p.month === month), locale),
      postScripts: '',
    };
  }

  for (const post of posts) {
    out[postSlug(post)] = {
      output: `${s.root}pages/daily/${postSlug(post)}.html`,
      lang: locale,
      title: `${extractTitle(readPost(post, locale), s.typeLabel[post.type])} • ${s.titleSuffix}`,
      assetsPrefix: locale === 'sv' ? '../../..' : '../..',
      indexHref: s.indexHrefFromPost,
      backLinkText: s.backLink,
      headExtras: '',
      mainContent: renderPostContent(post, locale),
      postScripts: '',
    };
  }

  return out;
}

module.exports = {
  template: 'standard',
  locales: (() => {
    const posts = discoverPosts();
    const months = [...new Set(posts.map((p) => p.month))].sort().reverse();
    return {
      en: buildLocale(posts, months, 'en'),
      sv: buildLocale(posts, months, 'sv'),
    };
  })(),
};
