// Daily AI content (generated by the Telegram agent's cron jobs).
// Posts live in src/content/daily/ as YYYY-MM-DD.<type>.en.html where
// <type> is "onthisday" or "ainews". Renders one page per post, an index
// at pages/daily.html with the most recent posts, and monthly archive
// pages at pages/daily/archive-YYYY-MM.html.
const fs = require('fs');
const path = require('path');

const DAILY_SRC = path.join(__dirname, '..', 'daily');
const RECENT_LIMIT = 14;

const TYPE_META = {
  onthisday: { label: 'On this day', badge: 'bg-cyan-900 text-cyan-300' },
  ainews: { label: 'AI news', badge: 'bg-amber-900 text-amber-300' },
};

function discoverPosts() {
  if (!fs.existsSync(DAILY_SRC)) return [];
  return fs
    .readdirSync(DAILY_SRC)
    .map((f) => {
      const m = f.match(/^(\d{4}-\d{2}-\d{2})\.(onthisday|ainews)\.en\.html$/);
      return m ? { file: f, date: m[1], month: m[1].slice(0, 7), type: m[2] } : null;
    })
    .filter(Boolean)
    .sort((a, b) => (a.date === b.date ? a.type.localeCompare(b.type) : b.date.localeCompare(a.date)));
}

function extractTitle(html, fallback) {
  const m = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  if (!m) return fallback;
  return m[1].replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim() || fallback;
}

function extractExcerpt(html) {
  const m = html.match(/<p[^>]*>([\s\S]*?)<\/p>/i);
  if (!m) return '';
  const text = m[1].replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim();
  return text.length > 180 ? text.slice(0, 180).trimEnd() + '…' : text;
}

function postSlug(post) {
  return `${post.date}-${post.type}`;
}

function monthLabel(month) {
  const [y, m] = month.split('-').map(Number);
  return new Intl.DateTimeFormat('en-GB', { month: 'long', year: 'numeric' }).format(new Date(y, m - 1, 1));
}

function renderCard(post, hrefPrefix) {
  const html = fs.readFileSync(path.join(DAILY_SRC, post.file), 'utf8');
  const meta = TYPE_META[post.type];
  const title = extractTitle(html, meta.label);
  const excerpt = extractExcerpt(html);
  return `
        <a href="${hrefPrefix}${postSlug(post)}.html" class="glass-card p-6 rounded-xl block hover:border-indigo-400 transition">
          <div class="flex items-center gap-3 mb-2">
            <span class="${meta.badge} text-xs font-semibold px-2 py-1 rounded">${meta.label.toUpperCase()}</span>
            <span class="text-slate-400 text-sm">${post.date}</span>
          </div>
          <h2 class="text-xl font-bold">${title}</h2>
          <p class="text-slate-400 mt-2">${excerpt}</p>
        </a>`;
}

function renderIndexContent(posts, months) {
  if (posts.length === 0) {
    return `
    <div class="container mx-auto px-4 max-w-3xl">
      <h1 class="text-4xl font-bold mb-6">Daily AI</h1>
      <p class="text-slate-400">No posts yet. New essays and news summaries appear here every day.</p>
    </div>`;
  }
  const cards = posts.slice(0, RECENT_LIMIT).map((p) => renderCard(p, 'daily/')).join('\n');
  const archiveLinks = months
    .map((m) => {
      const count = posts.filter((p) => p.month === m).length;
      return `<a href="daily/archive-${m}.html" class="text-cyan-400 hover:text-cyan-300 transition">${monthLabel(m)} (${count})</a>`;
    })
    .join('<span class="text-slate-600 mx-2">·</span>');
  return `
    <div class="container mx-auto px-4 max-w-3xl">
      <h1 class="text-4xl font-bold mb-2">Daily AI</h1>
      <p class="text-slate-400 mb-10">A short essay on this day in computing history and a daily AI news roundup, published automatically.</p>
      <div class="space-y-6">
${cards}
      </div>
      <div class="mt-12 pt-6 border-t border-slate-800">
        <h2 class="text-lg font-bold mb-3 text-slate-300">Archive</h2>
        <p>${archiveLinks}</p>
      </div>
    </div>`;
}

function renderArchiveContent(month, posts) {
  const cards = posts.map((p) => renderCard(p, '')).join('\n');
  return `
    <div class="container mx-auto px-4 max-w-3xl">
      <h1 class="text-4xl font-bold mb-2">Daily AI — ${monthLabel(month)}</h1>
      <p class="text-slate-400 mb-10">${posts.length} post${posts.length === 1 ? '' : 's'}.</p>
      <div class="space-y-6">
${cards}
      </div>
      <div class="mt-10">
        <a href="../daily.html" class="text-cyan-400 hover:text-cyan-300 transition">&larr; All daily posts</a>
      </div>
    </div>`;
}

function renderPostContent(post) {
  const html = fs.readFileSync(path.join(DAILY_SRC, post.file), 'utf8');
  const meta = TYPE_META[post.type];
  return `
    <div class="container mx-auto px-4 max-w-3xl">
      <div class="flex items-center gap-3 mb-6">
        <span class="${meta.badge} text-xs font-semibold px-2 py-1 rounded">${meta.label.toUpperCase()}</span>
        <span class="text-slate-400 text-sm">${post.date}</span>
      </div>
      <article class="prose-invert space-y-4 text-slate-300 daily-article">
${html}
      </article>
      <div class="mt-10">
        <a href="../daily.html" class="text-cyan-400 hover:text-cyan-300 transition">&larr; All daily posts</a>
      </div>
    </div>`;
}

module.exports = {
  template: 'standard',
  locales: (() => {
    const posts = discoverPosts();
    const months = [...new Set(posts.map((p) => p.month))].sort().reverse();
    const en = {};

    en.__index = {
      output: 'pages/daily.html',
      lang: 'en',
      title: 'Daily AI • Museum of AI',
      assetsPrefix: '..',
      indexHref: '../index.html',
      backLinkText: '← Back to Home',
      headExtras: '',
      mainContent: renderIndexContent(posts, months),
      postScripts: '',
    };

    for (const month of months) {
      en[`__archive_${month}`] = {
        output: `pages/daily/archive-${month}.html`,
        lang: 'en',
        title: `Daily AI ${monthLabel(month)} • Museum of AI`,
        assetsPrefix: '../..',
        indexHref: '../../index.html',
        backLinkText: '← Back to Home',
        headExtras: '',
        mainContent: renderArchiveContent(month, posts.filter((p) => p.month === month)),
        postScripts: '',
      };
    }

    for (const post of posts) {
      en[postSlug(post)] = {
        output: `pages/daily/${postSlug(post)}.html`,
        lang: 'en',
        title: `${extractTitle(fs.readFileSync(path.join(DAILY_SRC, post.file), 'utf8'), TYPE_META[post.type].label)} • Museum of AI`,
        assetsPrefix: '../..',
        indexHref: '../../index.html',
        backLinkText: '← Back to Home',
        headExtras: '',
        mainContent: renderPostContent(post),
        postScripts: '',
      };
    }

    return { en };
  })(),
};
